const theme_styles = {
  PRIMARY_COLOR: '#50C2C9',
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  BACKGROUND_COLOR_LIGHT: '#E6E6E6',
  FONT_COLOR: '#000000',
  LIGHT_COLOR: '#FFFFFF',
  BLACK_COLOR: '#000000',
  CONTAINER_PADDING: 20,
};
export default theme_styles;
